// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlMonitor.Data;

#nullable disable

namespace UrlMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602221914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UrlMonitor.Models.CheckResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrlTargetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VerificadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrlTargetId");

                    b.ToTable("CheckResults");
                });

            modelBuilder.Entity("UrlMonitor.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlTargetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrlTargetId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("UrlMonitor.Models.UrlTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UrlTargets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 19, 13, 361, DateTimeKind.Utc).AddTicks(8124),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 60,
                            Nome = "Google",
                            TimeoutSeconds = 10,
                            Url = "https://www.google.com"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 19, 13, 361, DateTimeKind.Utc).AddTicks(8171),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 120,
                            Nome = "GitHub",
                            TimeoutSeconds = 10,
                            Url = "https://github.com"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 19, 13, 361, DateTimeKind.Utc).AddTicks(8306),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 60,
                            Nome = "Exemplo Offline",
                            TimeoutSeconds = 5,
                            Url = "https://this-url-does-not-exist-xyz.com"
                        });
                });

            modelBuilder.Entity("UrlMonitor.Models.CheckResult", b =>
                {
                    b.HasOne("UrlMonitor.Models.UrlTarget", "UrlTarget")
                        .WithMany()
                        .HasForeignKey("UrlTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UrlTarget");
                });

            modelBuilder.Entity("UrlMonitor.Models.Incident", b =>
                {
                    b.HasOne("UrlMonitor.Models.UrlTarget", "UrlTarget")
                        .WithMany()
                        .HasForeignKey("UrlTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UrlTarget");
                });
#pragma warning restore 612, 618
        }
    }
}
