// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlMonitor.Data;

#nullable disable

namespace UrlMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UrlMonitor.Models.CheckResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrlTargetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VerificadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrlTargetId");

                    b.ToTable("CheckResults");
                });

            modelBuilder.Entity("UrlMonitor.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlTargetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrlTargetId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("UrlMonitor.Models.UrlTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UrlTargets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3724),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 60,
                            Nome = "GitHub",
                            TimeoutSeconds = 10,
                            Url = "https://github.com"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3730),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 60,
                            Nome = "Cloudflare",
                            TimeoutSeconds = 10,
                            Url = "https://www.cloudflare.com"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3733),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 60,
                            Nome = "Vercel",
                            TimeoutSeconds = 10,
                            Url = "https://vercel.com"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3736),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 120,
                            Nome = "NPM Registry",
                            TimeoutSeconds = 10,
                            Url = "https://registry.npmjs.org"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3738),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 60,
                            Nome = "Google",
                            TimeoutSeconds = 10,
                            Url = "https://www.google.com"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3741),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 120,
                            Nome = "AWS",
                            TimeoutSeconds = 10,
                            Url = "https://aws.amazon.com"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3743),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 60,
                            Nome = "Nubank",
                            TimeoutSeconds = 10,
                            Url = "https://nubank.com.br"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3745),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 60,
                            Nome = "iFood",
                            TimeoutSeconds = 10,
                            Url = "https://www.ifood.com.br"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3747),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 120,
                            Nome = "G1 Globo",
                            TimeoutSeconds = 10,
                            Url = "https://g1.globo.com"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3750),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 120,
                            Nome = "Mercado Livre",
                            TimeoutSeconds = 10,
                            Url = "https://www.mercadolivre.com.br"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3752),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 120,
                            Nome = "Banco do Brasil",
                            TimeoutSeconds = 10,
                            Url = "https://www.bb.com.br"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 2, 22, 45, 17, 581, DateTimeKind.Utc).AddTicks(3754),
                            ExpectedStatusCode = 200,
                            IntervalSeconds = 180,
                            Nome = "Receita Federal",
                            TimeoutSeconds = 15,
                            Url = "https://www.gov.br/receitafederal"
                        });
                });

            modelBuilder.Entity("UrlMonitor.Models.CheckResult", b =>
                {
                    b.HasOne("UrlMonitor.Models.UrlTarget", "UrlTarget")
                        .WithMany()
                        .HasForeignKey("UrlTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UrlTarget");
                });

            modelBuilder.Entity("UrlMonitor.Models.Incident", b =>
                {
                    b.HasOne("UrlMonitor.Models.UrlTarget", "UrlTarget")
                        .WithMany()
                        .HasForeignKey("UrlTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UrlTarget");
                });
#pragma warning restore 612, 618
        }
    }
}
